lightOption: 1
motionOption: 1
numReminder: 0
numSnooze: 2
restOption: 1
restPeriod: 5
restPersonalized: ''
soundOption: 1
username: Buddy
workOption: 1
workPeriod: 25
workPersonalized: ''
lastUsedDay: ['', '']