lastUsedDay: ['', '']
lightOption: 1
motionOption: 2
numReminder: 0
numSnooze: 0
restOption: 2
restPeriod: 20
restPersonalized: Have you taken a physical break away from your computer?
soundOption: 1
username: Charles
workOption: 1
workPeriod: 50
workPersonalized: ''
